#!/usr/bin/env node
import { assemble } from "./index.js";

// Test simple 6502 assembly
const testProgram = `
        ORG $1000
START   LDA #$00
        STA $2000
        INX
        BNE START
        RTS
`;

console.log("Testing EDASM assembler...\n");

try {
  const result = assemble(testProgram, { listing: true });

  console.log("Assembly successful!");
  console.log(`Generated ${result.bytes.length} bytes`);
  console.log("\nSymbol table:");
  for (const [name, value] of Object.entries(result.symbols)) {
    console.log(`  ${name} = $${value.toString(16).toUpperCase()}`);
  }

  console.log("\nGenerated bytes:");
  const hexBytes = Array.from(result.bytes)
    .map((b) => b.toString(16).padStart(2, "0").toUpperCase())
    .join(" ");
  console.log(`  ${hexBytes}`);

  if (result.listing) {
    console.log("\nListing:");
    console.log(result.listing);
  }

  // Verify expected output
  console.log("\nVerification:");
  const expected = [
    0xa9,
    0x00, // LDA #$00
    0x8d,
    0x00,
    0x20, // STA $2000
    0xe8, // INX
    0xd0,
    0xf8, // BNE (relative -8)
    0x60, // RTS
  ];

  let passed = true;
  let details = [];

  if (result.bytes.length !== expected.length) {
    details.push(
      `  ❌ Length mismatch: expected ${expected.length} bytes, got ${result.bytes.length}`,
    );
    passed = false;
  } else {
    for (let i = 0; i < expected.length; i++) {
      if (result.bytes[i] !== expected[i]) {
        details.push(
          `  ❌ Byte ${i}: expected $${expected[i].toString(16).toUpperCase()}, got $${result.bytes[i].toString(16).toUpperCase()}`,
        );
        passed = false;
      }
    }
  }

  if (passed) {
    console.log("  ✅ All bytes match expected output!");
  } else {
    for (const detail of details) {
      console.log(detail);
    }
  }

  console.log("\nExpected bytes:");
  const expectedHex = expected
    .map((b) => b.toString(16).padStart(2, "0").toUpperCase())
    .join(" ");
  console.log(`  ${expectedHex}`);
} catch (error) {
  console.error("Assembly failed:", error);
  process.exit(1);
}
